bucket_definitions:
  user_todos: # name for the bucket
    # Parameter Query, selecting a user_id parameter:
    parameters: SELECT request.user_id() as user_id
    data: # Data Query, selecting data
      - SELECT * FROM todo WHERE owner_id = bucket.user_id
  objects:
    parameters: SELECT request.user_id() as user_id
    data:
      - SELECT * FROM object WHERE owner_id = bucket.user_id
  object_updates:
    parameters: SELECT request.user_id() as user_id
    data:
      - SELECT id, owner_id, object_id, base64(update_data) as update_data, created_at FROM object_update WHERE owner_id = bucket.user_id
